

//  Config.h

#define SINCH_APPLICATION_KEY @"ecf5940f-523b-4271-a469-2512c56561e7"

#define SINCH_APPLICATION_SECRET @"Dj6/VR7pKU68z4WZ5gVBAw=="

#define SINCH_ENVIRONMENT_HOST @"sandbox.sinch.com"

#define PARSE_APPLICATION_ID @"your-app-id"

#define PARSE_CLIENT_KEY @"your-client-key"

#define SINCH_MESSAGE_RECIEVED @"SINCH_MESSAGE_RECIEVED"
#define SINCH_MESSAGE_SENT @"SINCH_MESSAGE_SENT"
#define SINCH_MESSAGE_DELIVERED @"SINCH_MESSAGE_DELIVERED"
#define SINCH_MESSAGE_FAILED @"SINCH_MESSAGE_DELIVERED"
